config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :booking_types
  resources :bookings, except: [:index, :new]

  post "payment-intent", to: "bookings#intent"
  get ":booking_link", to: "users#show", as: :user

  scope '/:booking_link', as: :user do
    resources :bookings, only: [:index, :new]
  end

  resources :webhooks, only: :create

  root to: "home#index"
end

app/controllers/booking_types_controller.rb
class BookingTypesController < ApplicationController
  before_action :set_booking_type, only: %i[ show edit update destroy ]

  # GET /booking_types or /booking_types.json
  def index
    @booking_types = current_user.booking_types
  end

  # GET /booking_types/1 or /booking_types/1.json
  def show
  end

  # GET /booking_types/new
  def new
    @booking_type = current_user.booking_types.new
  end

  # GET /booking_types/1/edit
  def edit
  end

  # POST /booking_types or /booking_types.json
  def create
    @booking_type = current_user.booking_types.new(booking_type_params)

    respond_to do |format|
      if @booking_type.save
        format.html { redirect_to root_path, notice: "Booking type was successfully created." }

      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_types/1 or /booking_types/1.json
  def update
    respond_to do |format|
      if @booking_type.update(booking_type_params)
        format.html { redirect_to root_path, notice: "Booking type was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_types/1 or /booking_types/1.json
  def destroy
    @booking_type.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Booking type was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_type
      @booking_type = BookingType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_type_params
      params.require(:booking_type).permit(:name, :location, :description, :color, :duration, :payment_required, :price)
    end
end

app/helpers/booking_types_helper.rb
module BookingTypesHelper
  def duration(type)
    if type.duration == 60
      "1 hr"
    else
      type.duration.to_formatted_s + " mins"
    end
  end
end

app/views/booking_types/_booking_type.html.erb
<div id="<%= dom_id booking_type %>">
  <%= link_to edit_booking_type_path(booking_type), class: "p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: <%= booking_type.color %>"></div>
    <h3 class="font-medium text-2xl"><%= booking_type.name %></h3>
    <p class="text-gray-500">View booking page</p>
    <p><%= duration(booking_type) %></p>

    <% if booking_type.payment_required? %>
      <div class="mt-3 pt-3 border-t">
        <p>
          <strong>Payment required</strong>
        </p>
        <p>
          <strong>Price:</strong>
          <%= number_to_currency(booking_type.price) %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/booking_types/_form.html.erb
<%= form_with(model: booking_type) do |form| %>
  <% if booking_type.errors.any? %>
    <div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
      <h2 class="text-lg font-semibold mb-3"><%= pluralize(booking_type.errors.count, "error") %> prohibited this booking_type from being saved:</h2>

      <ul class="list-disc leading-relaxed">
        <% booking_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, class: label_class %>
    <%= form.text_field :name, class: input_class %>
  </div>

  <div class="mb-6">
    <%= form.label :location, class: label_class %>
    <%= form.text_field :location, class: input_class %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: label_class %>
    <%= form.rich_text_area :description, class: input_class %>
  </div>

  <div class="mb-6">
    <%= form.label :color, class: label_class %>
    <%= form.text_field :color, class: input_class %>
  </div>

  <div class="mb-6">
    <%= form.label :duration, class: label_class %>
    <%= form.number_field :duration, class: input_class %>
  </div>

  <div class="mb-6 flex items-center space-x-2">
    <%= form.check_box :payment_required, class: checkbox_class %>
    <%= form.label :payment_required, class: label_class %>

  </div>

  <div class="mb-6 lg:w-1/4">
    <%= form.label :price, class: label_class %>
    <%= form.number_field :price, class: input_class %>
  </div>

  <%= form.submit class: button_class(theme: 'primary') %>

  <% if booking_type.persisted? %>
    <%= link_to "Cancel", booking_type, class: "text-neutral-700 underline inline-block ml-3" %>
  <% else %>
    <%= link_to "Cancel", booking_types_path, class:  "text-neutral-700 underline inline-block ml-3" %>
  <% end %>
<% end %>

app/views/booking_types/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="font-bold text-3xl mb-6">Edit booking type</h1>
    <% if current_user.booking_link? %>
      <%= link_to "View live page", user_path(booking_link: current_user.booking_link), class: "text-gray-700 underline" %>
    <% end%>
  </div>

  <%= render 'form', booking_type: @booking_type %>
</div>

app/views/booking_types/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="font-bold text-3xl mb-6">Create a booking type</h1>
    <% if current_user.booking_link? %>
      <%= link_to "View live page", user_path(booking_link: current_user.booking_link), class: "text-gray-700 underline" %>
    <% end%>
  </div>

  <%= render 'form', booking_type: @booking_type %>
</div>

app/views/booking_types/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Booking_type</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to booking_types_path, class: button_class(theme: "transparent") do %>
      All Booking_types
      <% end %>
      <%= link_to edit_booking_type_path(@booking_type), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @booking_type.name %></p>
      </li>
      <li>
        <p class="font-semibold">Location:</p>
        <p><%= @booking_type.location %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @booking_type.description %></p>
      </li>
      <li>
        <p class="font-semibold">Color:</p>
        <p><%= @booking_type.color %></p>
      </li>
      <li>
        <p class="font-semibold">Duration:</p>
        <p><%= @booking_type.duration %></p>
      </li>
      <li>
        <p class="font-semibold">Payment required:</p>
        <p><%= @booking_type.payment_required %></p>
      </li>
      <li>
        <p class="font-semibold">Price:</p>
        <p><%= @booking_type.price %></p>
      </li>
      <li>
        <p class="font-semibold">User:</p>
        <p><%= @booking_type.user %></p>
      </li>
  </ul>
</div>