config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :booking_types
  resources :bookings, except: [:index, :new]

  post "payment-intent", to: "bookings#intent"
  get ":booking_link", to: "users#show", as: :user

  scope '/:booking_link', as: :user do
    resources :bookings, only: [:index, :new]
  end

  resources :webhooks, only: :create

  root to: "home#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_person_name
  belongs_to :booking_type
  has_rich_text :notes

  validates :start_at, :end_at, :booking_type_id, :name, :email, presence: true

  enum status: { pending: 0, approved: 1, unapproved: 2 }
end

app/models/booking_type.rb
class BookingType < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_many :bookings
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @booking_type = BookingType.find_by(name: params[:booking_type])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking_type = BookingType.find(params[:booking][:booking_type_id])

    respond_to do |format|
      if @booking.save

        unless @booking_type.payment_required?
          @booking.approved!
        end

        format.html { redirect_to root_url, notice: "Booking was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to root_url, notice: "Booking was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def intent
    @booking_type = BookingType.find(params[:_json])
    amount = @booking_type.price * 100

    payment_intent = Stripe::PaymentIntent.create(
      amount: amount,
      currency: 'usd',
      automatic_payment_methods: {
        enabled: true
      },
      metadata: {
        user_id: @booking_type.user.id,
        booking_type_id: @booking_type.id
      }
    )

    respond_to do |format|
      format.json { render json: { clientSecret: payment_intent['client_secret'] } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:booking_type_id, :status, :name, :email, :start_at, :end_at, :notes)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<tr id="<%= dom_id booking %>">
  <td class="border border-slate-300 bg-white text-left p-4">
    <%= form_with(model: booking, method: :patch) do |form| %>
      <%= form.select :status, options_for_select(Booking.statuses.map { |key, value| [key.capitalize, key] }, form.object.status), {}, { class: input_class, onchange: "this.form.submit()"} %>
    <% end %>
  </td>
  <td class="border border-slate-300 bg-white text-left p-4"><%= booking.name %></td>
  <td class="border border-slate-300 bg-white text-left p-4"><%= booking.email %></td>
  <td class="border border-slate-300 bg-white text-left p-4"><%= booking.start_at.strftime('%b %e, %Y at %l:%M %p') %></td>
  <td class="border border-slate-300 bg-white text-left p-4"><%= booking.end_at.strftime('%b %e, %Y at %l:%M %p') %></td>
  <td class="border border-slate-300 bg-white text-left p-4"><%= booking.booking_type.name %></td>
  <td class="border border-slate-300 bg-white text-left p-4"><%= booking.booking_type.payment_required? ? "Yes" : "No" %></td>
  <td class="border border-slate-300 bg-white text-left p-4"><%= booking.customer_paid? ? "Yes" : "No" %></td>
</tr>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, data: { turbo: false, action: "submit->payment#purchase", payment_target: "form"}) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
      <h2 class="text-lg font-semibold mb-3"><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul class="list-disc leading-relaxed">
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="font-bold text-lg mb-3 mt-6">Personal details</h3>

  <div class="grid grid-col-1 lg:grid-cols-2 gap-6 mb-10">
    <div>
      <%= form.label :name, class: label_class %>
      <%= form.text_field :name, class: input_class, data: { payment_target: "name" } %>
    </div>

    <div>
      <%= form.label :email, class: label_class %>
      <%= form.text_field :email, class: input_class, data: { payment_target: "email" } %>
    </div>
  </div>

  <div class="mb-6">
    <%= form.label :notes, class: label_class %>
    <%= form.rich_text_area :notes, class: input_class %>
  </div>

  <h3 class="font-bold text-lg mb-3">Booking details</h3>

  <% if @booking.new_record? %>
    <div class="mb-6">
      <div class="rounded border-slate-300 border shadow-sm bg-white py-6 px-10 inline-block relative">
        <%= form.label :booking_type_id, "Booking type", class: label_class %>
        <input type="hidden" name="booking[booking_type_id]" value="<%= @booking_type.id %>">
        <div class="flex items-start">
          <div class="text-3xl font-bold mr-3"><%= params[:booking_type] %>
            <div class="absolute top-3 right-3 w-3 h-3 rounded-full" style="background-color: <%= @booking_type.color %>;"></div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <%= @booking.booking_type.name %>
  <% end %>

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-10">
    <div>
      <%= form.label :start_at, class: label_class %>
      <%= form.datetime_field :start_at, class: input_class, min: Date.today %>
    </div>

    <div>
      <%= form.label :end_at, class: label_class %>
      <%= form.datetime_field :end_at, class: input_class, min: Date.today %>
    </div>
  </div>

  <%= form.submit @booking_type.payment_required? ? "Schedule booking for #{number_to_currency(@booking_type.price)}" : "Schedule booking", class: button_class(theme: 'primary'), data: { payment_target: "submit" } %>
<% end %>

app/views/bookings/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit booking</h1>
    <% if @booking.persisted? %>
    <%= button_to 'Destroy', @booking, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', booking: @booking %>
</div>

app/views/bookings/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Bookings</h1>

    <%= link_to new_booking_path, class: button_class(theme: "primary") do %>
    Add New Booking
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Status</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">First name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Last name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Email</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Start at</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">End at</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
      <%= content_tag :tr, id: dom_id(booking), class: dom_class(booking) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.status %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.first_name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.last_name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.email %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.start_at %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.end_at %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', booking %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/bookings/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <% if @booking_type.payment_required? %>
    <div
      data-controller="payment"
      data-payment-item-value="<%= @booking_type.id %>"
      data-payment-return-url-value="<%= root_url %>"
    >
      <h1 class="font-bold text-3xl mb-6">Schedule your booking for <%= number_to_currency(@booking_type.price) %></h1>

      <div clas="mb-10">
        <h3 class="font-bold text-xl mb-3">Enter payment details</h3>

        <div id="payment-element" data-payment-target="element"></div>

        <div data-payment-target="message" class="hidden"></div>
      </div>

      <%= render 'form', booking: @booking %>
    </div>
  <% else %>
    <h1 class="font-bold text-3xl mb-6">Schedule your booking</h1>

    <%= render 'form', booking: @booking %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Booking</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to bookings_path, class: button_class(theme: "transparent") do %>
      All Bookings
      <% end %>
      <%= link_to edit_booking_path(@booking), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Status:</p>
        <p><%= @booking.status %></p>
      </li>
      <li>
        <p class="font-semibold">First name:</p>
        <p><%= @booking.first_name %></p>
      </li>
      <li>
        <p class="font-semibold">Last name:</p>
        <p><%= @booking.last_name %></p>
      </li>
      <li>
        <p class="font-semibold">Email:</p>
        <p><%= @booking.email %></p>
      </li>
      <li>
        <p class="font-semibold">Start at:</p>
        <p><%= @booking.start_at %></p>
      </li>
      <li>
        <p class="font-semibold">End at:</p>
        <p><%= @booking.end_at %></p>
      </li>
  </ul>
</div>