config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :booking_types
  resources :bookings, except: [:index, :new]

  post "payment-intent", to: "bookings#intent"
  get ":booking_link", to: "users#show", as: :user

  scope '/:booking_link', as: :user do
    resources :bookings, only: [:index, :new]
  end

  resources :webhooks, only: :create

  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :booking_types

  validates :booking_link, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(booking_link: params[:booking_link])
  end
end

app/views/users/_booking_type.html.erb
<div id="<%= dom_id booking_type %>">
  <%= link_to new_user_booking_path(booking_link: @user.booking_link, booking_type: booking_type.name.parameterize), class: "p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: <%= booking_type.color %>"></div>
    <h3 class="font-medium text-2xl"><%= booking_type.name %></h3>
    <p class="text-gray-500">View booking page</p>
    <p><%= duration(booking_type) %></p>

    <% if booking_type.payment_required? %>
      <div class="mt-3 pt-3 border-t">
        <p>
          <strong>Payment required</strong>
        </p>
        <p>
          <strong>Price:</strong>
          <%= number_to_currency(booking_type.price) %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="max-w-5xl mx-auto pb-8 rounded shadow-xl border">
  <div class="px-6 py-10 rounded-t-xl bg-gray-50">
    <h1 class="text-3xl font-extrabold text-center"><%= @user.name %>'s Booking Page</h1>
    <p class="text-center text-gray-600 mt-2">Book your prefered time slot using the booking options below.</p>
  </div>
  <div class="grid grid-cols-3 gap-6 px-8 pt-8">
    <% @user.booking_types.each do |booking_type| %>
      <%= render "users/booking_type", booking_type: booking_type %>
    <% end %>
  </div>
</div>